GameBlog/Models/Newsletter.cs
using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;

namespace GameBlog.Models
{
    [Index("Email", IsUnique = true)]
    public class Newsletter
    {
        public int Id { get; set; }
        
        [Required]
        
        public string Email { get; set; }
        [Required]
        public DateTime CreatedAt { get; set; }
        [Required]
        public DateTime UpdatedAt { get; set; }
    }
}

GameBlog/Controllers/Blog/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GameBlog.Models;
using GameBlog.Models.Blog;
using GameBlog.Repositories;
using GameBlog.ViewModel.Blog;

namespace GameBlog.Controllers.Blog
{
    [Route("blog")]
    public class BlogPostsController : Controller
    {
        private readonly IGenericRepository<Post> _repoPosts;

        public BlogPostsController(IGenericRepository<Post> repoPosts)
        {
            _repoPosts = repoPosts;
        }

        [Route("all-posts")]
        public async Task<IActionResult> Index([FromQuery] int pageN = 1)
        {
            var count = _repoPosts.Count();
            if (count <= 0)
            {
                return RedirectToAction("Index", "Error",
                    new {errors = "No posts"});
            }

            var pagination = new Pagination(count, pageN, ControllerContext.ActionDescriptor.ControllerName);

            var includes = new List<Expression<Func<Post, object>>>
            {
                p => p.Author,
                p => p.Category
            };
            var posts = await _repoPosts.GetAllAsync(includes);
            posts = posts.Skip((pageN - 1) * pagination.PageSize).Take(pagination.PageSize).OrderByDescending(p => p.CreatedAt);

            var viewModel = new BlogPostIndexViewModel
            {
                BlogPosts = posts,
                Pagination = pagination
            };

            return View(viewModel);
        }

        // Get Show page with slug
        [Route("{postSlug}")]
        public async Task<IActionResult> Show([FromRoute] string postSlug)
        {
            var includes = new List<Expression<Func<Post, object>>>
            {
                p => p.Author,
                p => p.Category,
                p => p.BlogPostImages
            };
            var post = await _repoPosts.GetBySlugAsync(postSlug, includes);
            if (post == null)
                return RedirectToAction("Index", "Error",
                    new {errors = "No post"});


            var viewModel = new BlogPostShowViewModel
            {
                CreatedAt = post.CreatedAt,
                UpdatedAt = post.UpdatedAt,
                MetaDescription = post.MetaDescription,
                MetaKeywords = post.MetaKeywords,
                Name = post.Name,
                Slug = post.Slug,
                Description = post.Description,
                Article = post.Article,
                BlogPostImages = post.BlogPostImages,
                Category = post.Category,
                Author = post.Author,
                Views = post.Views,
                Image = post.Image
            };
            return View(viewModel);
        }
    }
}

GameBlog/Controllers/PagesController.cs
using System;
using System.Threading.Tasks;
using GameBlog.Data;
using GameBlog.Models;
using GameBlog.ViewModel;
using MailKit.Net.Smtp;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using MimeKit;

namespace GameBlog.Controllers
{
    public class PagesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IConfiguration _configuration;

        public PagesController(ApplicationDbContext context, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;
        }

        public IActionResult Contact()
        {
            var contactFormViewModel = new ContactFormViewModel();
            return View(contactFormViewModel);
        }


        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Contact([FromForm] ContactFormViewModel model)
        {
            if (ModelState.IsValid)
            {
                var message = new ContactMessage()
                {
                    Email = model.Email,
                    Message = model.Message,
                    Name = model.Name,
                    Subject = model.Subject,
                    CreatedAt = DateTime.Now,
                    UpdatedAt = DateTime.Now
                };
                _context.ContactMessages.Add(message);
                await _context.SaveChangesAsync();

                ViewData["contactMessage"] = "success";
            }
            else
            {
                ViewData["contactMessage"] = "error";
                return View(model);
            }


            var mailMessage = new MimeMessage();

            var to = _configuration["EmailService:To"];
            var host = _configuration["EmailService:Host"];
            var sender = _configuration["EmailService:Sender"];
            var password = _configuration["EmailService:Password"];

            mailMessage.From.Add(new MailboxAddress("Game Blog", sender));
            mailMessage.To.Add(new MailboxAddress("Admin Game Blog", to));
            mailMessage.Subject = model.Subject;

            mailMessage.Body = new TextPart()
            {
                Text = ":::from: " + model.Email + "\n:::name: " + model.Name + "\n:::message: " + model.Message
            };


            var c = new SmtpClient();

            await c.ConnectAsync(host, 465, true);
            await c.AuthenticateAsync(sender, password);
            await c.SendAsync(mailMessage);
            await c.DisconnectAsync(true);


            return View();
        }

        public IActionResult Privacy()
        {
            ViewData["Title"] = "Privacy page";
            return View();
        }


        public IActionResult Newsletter()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> NewsLetters([FromForm] string email)
        {
            try
            {
                var newsletter = new Newsletter()
                {
                    Email = email,
                    CreatedAt = DateTime.Now,
                    UpdatedAt = DateTime.Now
                };
                _context.Newsletters.Add(newsletter);
                await _context.SaveChangesAsync();

                return RedirectToAction("Newsletter");
            }
            catch (DbUpdateException e)
            {
                Console.WriteLine(e);
                throw;
            }
        }
    }
}

GameBlog/Views/Shared/Partial/_Footer.cshtml
<footer class="footer-section">
    <div class="container">
        <div class="footer-left-pic">
            <img src="/img/footer-left-pic.png" alt="">
        </div>
        <div class="footer-right-pic">
            <img src="/img/footer-right-pic.png" alt="">
        </div>
        <a href="#" class="footer-logo">
            <img src="/img/logo.png" alt="">
        </a>
        <ul class="main-menu footer-menu">
            <li>
                <a asp-controller="Pages" asp-action="Contact">Contact</a>
            </li>

            <li>
                <a asp-controller="Pages" asp-action="Privacy">Privacy</a>
            </li>
        </ul>
        <div class="footer-social d-flex justify-content-center">

            <a href="#">Facebook</a>

        </div>
        <div class="copyright"><a href="/">GameBlog</a> 2021</div>
    </div>
</footer>

GameBlog/Views/Shared/Partial/_Header.cshtml
<header class="header-section">
    <div class="header-warp">
        <div class="header-social d-flex justify-content-end">
            <p>Follow me:</p>
            <a href="#">F</a>
        </div>
        <div class="header-bar-warp d-flex">
            <a href="/" class="site-logo">
                <img src="/img/logo.png" alt="">
            </a>
            <nav class="top-nav-area w-100">
                <div class="user-panel">
                    @* <a href="#">Login</a> / <a href="#">Register</a> *@
                </div>
                <ul class="main-menu primary-menu">
                    <li>
                        <a asp-controller="BlogPosts" asp-action="Index">Blog</a>
                    </li>
                    <li>
                        <a asp-controller="Pages" asp-action="Contact">Contact</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</header>

GameBlog/Views/Shared/Partial/_NewsLetters.cshtml
<!-- Newsletter section -->
<section class="newsletter-section">
    <div class="container">
        <h2>Subscribe to newsletter</h2>
        <form class="newsletter-form"
              method="post"
              asp-controller="Pages"
              asp-action="NewsLetters">
            <input type="text" placeholder="ENTER YOUR E-MAIL" name="email">
            <button class="site-btn" 
                    type="submit">
                subscribe
                <img src="/img/icons/double-arrow.png" alt="subscribe image"/>
            </button>
        </form>
    </div>
</section>
<!-- Newsletter section end -->