GameBlog/Controllers/Blog/BlogCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GameBlog.Models;
using GameBlog.Models.Blog;
using GameBlog.Repositories;
using GameBlog.ViewModel.Blog;

namespace GameBlog.Controllers.Blog
{
    [Route("blog/categories")]
    public class BlogCategoriesController : Controller
    {
        private readonly IGenericRepository<Category> _repoCats;
        private readonly IGenericRepository<Post> _repoPosts;

        public BlogCategoriesController(
            IGenericRepository<Category> repoCats,
            IGenericRepository<Post> repoPosts
        )
        {
            _repoCats = repoCats;
            _repoPosts = repoPosts;
        }

        [Route("")]
        public async Task<IActionResult> Index([FromQuery] int pageN = 1)
        {
            var includes = new List<Expression<Func<Category, object>>>
            {
                c => c.Author,
                c => c.Posts
            };
            var count = _repoCats.Count();
            if (count <= 0)
                return RedirectToAction("Index", "Error",
                    new {errors = "Нет записей"});

            var pagination = new Pagination(count, pageN, ControllerContext.ActionDescriptor.ControllerName);

            var categories = await _repoCats.GetAllAsync(includes);
            categories = categories.Skip((pageN - 1) * pagination.PageSize).Take(pagination.PageSize);

            var viewModel = new BlogCategoryIndexViewModel
            {
                BlogCategories = categories,
                Pagination = pagination
            };


            return View(viewModel);
        }

        [Route("{slug}")]
        public async Task<IActionResult> Show([FromRoute] string slug, [FromQuery] int pageN = 1)
        {
            var includes = new List<Expression<Func<Category, object>>>
            {
                c => c.Author,
                c => c.Posts
            };

            var category = await _repoCats.GetBySlugAsync(slug, includes);

            if (category == null)
                return RedirectToAction("Index", "Error",
                    new {errors = "Категория не найдена"});

            var count = category.Posts.Count();
            if (count <= 0)
                return RedirectToAction("Index", "Error",
                    new {errors = "Нет записей в категории"});

            var pagination = new Pagination(count, pageN, ControllerContext.ActionDescriptor.ControllerName,
                ControllerContext.ActionDescriptor.ActionName);

            category.Posts = category
                .Posts
                .Skip((pageN - 1) * pagination.PageSize)
                .Take(pagination.PageSize)
                .ToList();

            var viewModel = new BlogCategoryShowViewModel
            {
                Category = category,
                BlogPosts = category.Posts,
                Pagination = pagination
            };

            return View(viewModel);
        }
    }
}

GameBlog/Controllers/Blog/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GameBlog.Models;
using GameBlog.Models.Blog;
using GameBlog.Repositories;
using GameBlog.ViewModel.Blog;

namespace GameBlog.Controllers.Blog
{
    [Route("blog")]
    public class BlogPostsController : Controller
    {
        private readonly IGenericRepository<Post> _repoPosts;

        public BlogPostsController(IGenericRepository<Post> repoPosts)
        {
            _repoPosts = repoPosts;
        }

        [Route("all-posts")]
        public async Task<IActionResult> Index([FromQuery] int pageN = 1)
        {
            var count = _repoPosts.Count();
            if (count <= 0)
            {
                return RedirectToAction("Index", "Error",
                    new {errors = "No posts"});
            }

            var pagination = new Pagination(count, pageN, ControllerContext.ActionDescriptor.ControllerName);

            var includes = new List<Expression<Func<Post, object>>>
            {
                p => p.Author,
                p => p.Category
            };
            var posts = await _repoPosts.GetAllAsync(includes);
            posts = posts.Skip((pageN - 1) * pagination.PageSize).Take(pagination.PageSize).OrderByDescending(p => p.CreatedAt);

            var viewModel = new BlogPostIndexViewModel
            {
                BlogPosts = posts,
                Pagination = pagination
            };

            return View(viewModel);
        }

        // Get Show page with slug
        [Route("{postSlug}")]
        public async Task<IActionResult> Show([FromRoute] string postSlug)
        {
            var includes = new List<Expression<Func<Post, object>>>
            {
                p => p.Author,
                p => p.Category,
                p => p.BlogPostImages
            };
            var post = await _repoPosts.GetBySlugAsync(postSlug, includes);
            if (post == null)
                return RedirectToAction("Index", "Error",
                    new {errors = "No post"});


            var viewModel = new BlogPostShowViewModel
            {
                CreatedAt = post.CreatedAt,
                UpdatedAt = post.UpdatedAt,
                MetaDescription = post.MetaDescription,
                MetaKeywords = post.MetaKeywords,
                Name = post.Name,
                Slug = post.Slug,
                Description = post.Description,
                Article = post.Article,
                BlogPostImages = post.BlogPostImages,
                Category = post.Category,
                Author = post.Author,
                Views = post.Views,
                Image = post.Image
            };
            return View(viewModel);
        }
    }
}

GameBlog/Views/BlogCategories/Index.cshtml
@model GameBlog.ViewModel.Blog.BlogCategoryIndexViewModel

@section metaTitle {Все категории в Блоге}

@section metaDesc {Выбирайте категорию в блоге и читайте последние новости из мира туризма от компании Нано Тревел}

@section metaKeys {блог о туризме, категории в блоге о туризме, записи о туризме, какие новости о туризме почитать}

<div class="container">
    <h2>Список всех категорий блога</h2>

    <div class="simple-listing">
        @foreach (var category in Model.BlogCategories)
        {
            <a asp-controller="BlogCategories"
               asp-action="Show"
               asp-route-slug="@category.Slug">
                <div class="simple-listing-item">
                    @category.Name
                </div>
            </a>
        }
    </div>

    <vc:pagination pagination="@Model.Pagination"/>
</div>

GameBlog/Views/BlogCategories/Show.cshtml
@model GameBlog.ViewModel.Blog.BlogCategoryShowViewModel

@section metaTitle {Категория @Model.Category.Name @(Model.Pagination.PageN > 1 ? Model.Pagination.PageN as object : "")}

@section metaDesc {@Model.Category.MetaDescription}

@section metaKeys {@Model.Category.MetaKeywords}

<div class="container">
    <h2>Список всех записей в категории "@Model.Category.Name"</h2>

    <div class="simple-listing">
        @foreach (var post in Model.BlogPosts)
        {
            <a asp-controller="BlogPosts"
               asp-action="Show"
               asp-route-postSlug="@post.Slug">
                <div class="simple-listing-item">
                    @post.Name
                </div>
            </a>
        }
    </div>

    <vc:pagination pagination="@Model.Pagination"/>
</div>